/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poletneznano;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author anjabrelih
 */
public class LetalskeKarte extends javax.swing.JFrame {
    
    Poizvedba poizvedba;

    /**
     * Creates new form ZacetnaStran1
     */
    public LetalskeKarte() {
        initComponents();
    }
    
    public void setPoizvedba(Poizvedba poizvedba){
        this.poizvedba=poizvedba;
        airportA.setText(poizvedba.getAirportA());
        airportA1.setText(poizvedba.getAirportA());
        airportA2.setText(poizvedba.getAirportA());
        airportA3.setText(poizvedba.getAirportA());
        airportB.setText(poizvedba.getAirportB());
        airportB1.setText(poizvedba.getAirportB());
        airportB2.setText(poizvedba.getAirportB());
        airportB3.setText(poizvedba.getAirportB());
        
        depDate.setText(poizvedba.getDateA());
        depDate1.setText(poizvedba.getDateB());
        arrDate.setText(poizvedba.getDateA());
        arrDate1.setText(poizvedba.getDateB());
        
        depDate2.setText(poizvedba.getDateA());
        depDate3.setText(poizvedba.getDateB());
        arrDate2.setText(poizvedba.getDateA());
        arrDate3.setText(poizvedba.getDateB());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        ticket1Panel = new javax.swing.JPanel();
        pricePanel = new javax.swing.JPanel();
        airportA4 = new javax.swing.JLabel();
        FlightDep = new javax.swing.JPanel();
        airportA = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        airportB = new javax.swing.JLabel();
        arrDate = new javax.swing.JLabel();
        arrivalTime = new javax.swing.JLabel();
        depDate = new javax.swing.JLabel();
        DepartureTime = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        FlightDep1 = new javax.swing.JPanel();
        airportB1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        airportA1 = new javax.swing.JLabel();
        arrDate1 = new javax.swing.JLabel();
        arrivalTime1 = new javax.swing.JLabel();
        depDate1 = new javax.swing.JLabel();
        DepartureTime1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ticket2Panel = new javax.swing.JPanel();
        FlightDep2 = new javax.swing.JPanel();
        airportA2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        airportB2 = new javax.swing.JLabel();
        arrDate2 = new javax.swing.JLabel();
        arrivalTime2 = new javax.swing.JLabel();
        depDate2 = new javax.swing.JLabel();
        DepartureTime2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        FlightDep3 = new javax.swing.JPanel();
        airportB3 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        airportA3 = new javax.swing.JLabel();
        arrDate3 = new javax.swing.JLabel();
        arrivalTime3 = new javax.swing.JLabel();
        depDate3 = new javax.swing.JLabel();
        DepartureTime3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        pricePanel1 = new javax.swing.JPanel();
        airportA7 = new javax.swing.JLabel();
        btnIzberi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnNazaj = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        DepDate4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DepDate5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        DepDate6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        DepDate7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(957, 736));

        background.setBackground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(0, 204, 204));
        titlePanel.setPreferredSize(new java.awt.Dimension(410, 88));

        title.setFont(new java.awt.Font("Myanmar Sangam MN", 1, 26)); // NOI18N
        title.setText("Polet v neznano");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(15, 15, 15))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        ticket1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 5));
        ticket1Panel.setPreferredSize(new java.awt.Dimension(779, 180));

        pricePanel.setBackground(new java.awt.Color(204, 255, 255));
        pricePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        airportA4.setFont(new java.awt.Font("Geeza Pro", 1, 24)); // NOI18N
        airportA4.setText("111 €");

        javax.swing.GroupLayout pricePanelLayout = new javax.swing.GroupLayout(pricePanel);
        pricePanel.setLayout(pricePanelLayout);
        pricePanelLayout.setHorizontalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pricePanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(airportA4)
                .addGap(65, 65, 65))
        );
        pricePanelLayout.setVerticalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pricePanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(airportA4)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        FlightDep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        airportA.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportA.setText("Letališče A");

        jLabel22.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel22.setText("-");

        airportB.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportB.setText("Letališče B");

        arrDate.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrDate.setText("Datum prihoda");

        arrivalTime.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrivalTime.setText("17:50");

        depDate.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        depDate.setText("Datum odhoda");

        DepartureTime.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        DepartureTime.setText("15:30");

        jLabel28.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel28.setText("Čas potovanja:");

        jLabel29.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel29.setText("2h 20min");

        javax.swing.GroupLayout FlightDepLayout = new javax.swing.GroupLayout(FlightDep);
        FlightDep.setLayout(FlightDepLayout);
        FlightDepLayout.setHorizontalGroup(
            FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
            .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDepLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FlightDepLayout.createSequentialGroup()
                            .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FlightDepLayout.createSequentialGroup()
                                    .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(airportA)
                                        .addComponent(depDate))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(DepartureTime))
                            .addGap(20, 20, 20)
                            .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(airportB)
                                .addComponent(arrDate)
                                .addComponent(arrivalTime)))
                        .addGroup(FlightDepLayout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel29)))
                    .addGap(37, 37, 37)))
        );
        FlightDepLayout.setVerticalGroup(
            FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDepLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airportA)
                        .addComponent(airportB)
                        .addComponent(jLabel22))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depDate)
                        .addComponent(arrDate))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DepartureTime)
                        .addComponent(arrivalTime))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addGroup(FlightDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29))
                    .addGap(22, 22, 22)))
        );

        FlightDep1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        airportB1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportB1.setText("Letališče B");

        jLabel23.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel23.setText("-");

        airportA1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportA1.setText("Letališče A");

        arrDate1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrDate1.setText("Datum prihoda");

        arrivalTime1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrivalTime1.setText("17:50");

        depDate1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        depDate1.setText("Datum odhoda");

        DepartureTime1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        DepartureTime1.setText("15:30");

        jLabel30.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel30.setText("Čas potovanja:");

        jLabel31.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel31.setText("2h 20min");

        javax.swing.GroupLayout FlightDep1Layout = new javax.swing.GroupLayout(FlightDep1);
        FlightDep1.setLayout(FlightDep1Layout);
        FlightDep1Layout.setHorizontalGroup(
            FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDep1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FlightDep1Layout.createSequentialGroup()
                            .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FlightDep1Layout.createSequentialGroup()
                                    .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(airportB1)
                                        .addComponent(depDate1))
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel23))
                                .addComponent(DepartureTime1))
                            .addGap(20, 20, 20)
                            .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(airportA1)
                                .addComponent(arrDate1)
                                .addComponent(arrivalTime1)))
                        .addGroup(FlightDep1Layout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel31)))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        FlightDep1Layout.setVerticalGroup(
            FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDep1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airportB1)
                        .addComponent(airportA1)
                        .addComponent(jLabel23))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depDate1)
                        .addComponent(arrDate1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DepartureTime1)
                        .addComponent(arrivalTime1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addGroup(FlightDep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31))
                    .addGap(22, 22, 22)))
        );

        javax.swing.GroupLayout ticket1PanelLayout = new javax.swing.GroupLayout(ticket1Panel);
        ticket1Panel.setLayout(ticket1PanelLayout);
        ticket1PanelLayout.setHorizontalGroup(
            ticket1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticket1PanelLayout.createSequentialGroup()
                .addComponent(FlightDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FlightDep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ticket1PanelLayout.setVerticalGroup(
            ticket1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FlightDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FlightDep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ticket2Panel.setPreferredSize(new java.awt.Dimension(779, 180));

        FlightDep2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FlightDep2.setPreferredSize(new java.awt.Dimension(299, 180));

        airportA2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportA2.setText("Letališče A");

        jLabel26.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel26.setText("-");

        airportB2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportB2.setText("Letališče B");

        arrDate2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrDate2.setText("Datum prihoda");

        arrivalTime2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrivalTime2.setText("19:30");

        depDate2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        depDate2.setText("Datum odhoda");

        DepartureTime2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        DepartureTime2.setText("12:10");

        jLabel32.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel32.setText("Čas potovanja:");

        jLabel33.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel33.setText("7h 20min");

        javax.swing.GroupLayout FlightDep2Layout = new javax.swing.GroupLayout(FlightDep2);
        FlightDep2.setLayout(FlightDep2Layout);
        FlightDep2Layout.setHorizontalGroup(
            FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDep2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FlightDep2Layout.createSequentialGroup()
                            .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FlightDep2Layout.createSequentialGroup()
                                    .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(airportA2)
                                        .addComponent(depDate2))
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel26))
                                .addComponent(DepartureTime2))
                            .addGap(20, 20, 20)
                            .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(airportB2)
                                .addComponent(arrDate2)
                                .addComponent(arrivalTime2)))
                        .addGroup(FlightDep2Layout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel33)))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        FlightDep2Layout.setVerticalGroup(
            FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDep2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airportA2)
                        .addComponent(airportB2)
                        .addComponent(jLabel26))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depDate2)
                        .addComponent(arrDate2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DepartureTime2)
                        .addComponent(arrivalTime2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addGroup(FlightDep2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel33))
                    .addGap(22, 22, 22)))
        );

        FlightDep3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FlightDep3.setPreferredSize(new java.awt.Dimension(299, 172));

        airportB3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportB3.setText("Letališče B");

        jLabel34.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel34.setText("-");

        airportA3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        airportA3.setText("Letališče A");

        arrDate3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrDate3.setText("Datum prihoda");

        arrivalTime3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        arrivalTime3.setText("19:30");

        depDate3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        depDate3.setText("Datum odhoda");

        DepartureTime3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        DepartureTime3.setText("12:10");

        jLabel36.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel36.setText("Čas potovanja:");

        jLabel37.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel37.setText("7h 20min");

        javax.swing.GroupLayout FlightDep3Layout = new javax.swing.GroupLayout(FlightDep3);
        FlightDep3.setLayout(FlightDep3Layout);
        FlightDep3Layout.setHorizontalGroup(
            FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDep3Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FlightDep3Layout.createSequentialGroup()
                            .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FlightDep3Layout.createSequentialGroup()
                                    .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(airportB3)
                                        .addComponent(depDate3))
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel34))
                                .addComponent(DepartureTime3))
                            .addGap(20, 20, 20)
                            .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(airportA3)
                                .addComponent(arrDate3)
                                .addComponent(arrivalTime3)))
                        .addGroup(FlightDep3Layout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel37)))
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        FlightDep3Layout.setVerticalGroup(
            FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FlightDep3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airportB3)
                        .addComponent(airportA3)
                        .addComponent(jLabel34))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depDate3)
                        .addComponent(arrDate3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DepartureTime3)
                        .addComponent(arrivalTime3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addGroup(FlightDep3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(jLabel37))
                    .addGap(22, 22, 22)))
        );

        pricePanel1.setBackground(new java.awt.Color(204, 255, 255));
        pricePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        airportA7.setFont(new java.awt.Font("Geeza Pro", 1, 24)); // NOI18N
        airportA7.setText("222 €");

        javax.swing.GroupLayout pricePanel1Layout = new javax.swing.GroupLayout(pricePanel1);
        pricePanel1.setLayout(pricePanel1Layout);
        pricePanel1Layout.setHorizontalGroup(
            pricePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pricePanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(airportA7)
                .addGap(70, 70, 70))
        );
        pricePanel1Layout.setVerticalGroup(
            pricePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pricePanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(airportA7)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ticket2PanelLayout = new javax.swing.GroupLayout(ticket2Panel);
        ticket2Panel.setLayout(ticket2PanelLayout);
        ticket2PanelLayout.setHorizontalGroup(
            ticket2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticket2PanelLayout.createSequentialGroup()
                .addComponent(FlightDep2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(FlightDep3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pricePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ticket2PanelLayout.setVerticalGroup(
            ticket2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FlightDep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FlightDep3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(pricePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnIzberi.setBackground(new java.awt.Color(0, 204, 204));
        btnIzberi.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnIzberi.setText("Izberi");
        btnIzberi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIzberi.setMaximumSize(new java.awt.Dimension(120, 40));
        btnIzberi.setMinimumSize(new java.awt.Dimension(100, 30));
        btnIzberi.setSize(new java.awt.Dimension(120, 40));
        btnIzberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzberiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel8.setText("Razvrsti:");

        jComboBox1.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cena", "hitrost" }));

        btnNazaj.setBackground(new java.awt.Color(242, 242, 242));
        btnNazaj.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnNazaj.setText("Nazaj");
        btnNazaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNazaj.setMaximumSize(new java.awt.Dimension(120, 40));
        btnNazaj.setMinimumSize(new java.awt.Dimension(100, 30));
        btnNazaj.setSize(new java.awt.Dimension(120, 40));
        btnNazaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazajActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(btnNazaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 608, Short.MAX_VALUE)
                                .addComponent(btnIzberi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ticket1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                            .addComponent(ticket2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ticket1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ticket2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzberi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNazaj, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jRadioButton1)
                        .addGap(196, 196, 196)
                        .addComponent(jRadioButton2)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel1.setMaximumSize(new java.awt.Dimension(340, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 20));

        DepDate4.setBackground(new java.awt.Color(255, 255, 255));
        DepDate4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate4.setForeground(new java.awt.Color(204, 255, 255));
        DepDate4.setText("1 Izbira leta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate4)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(DepDate4)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel2.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate5.setBackground(new java.awt.Color(255, 255, 255));
        DepDate5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate5.setText("2 Podatki");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(DepDate5)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(DepDate5)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel3.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate6.setBackground(new java.awt.Color(255, 255, 255));
        DepDate6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate6.setText("3 Plačilo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(DepDate6)
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(DepDate6)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel4.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate7.setBackground(new java.awt.Color(255, 255, 255));
        DepDate7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate7.setText("4 Zaključek");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(DepDate7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(DepDate7)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(987, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzberiActionPerformed
        // TODO add your handling code here:
        
        //IZBERI
        Potniki n = new Potniki();
        n.setVisible(true);
        n.setPoizvedba(poizvedba);
        this.dispose();
        
    }//GEN-LAST:event_btnIzberiActionPerformed

    private void btnNazajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazajActionPerformed
        // TODO add your handling code here:
        
        //NAZAJ
        if(poizvedba.getDateA1() == null){
            ZacetnaStran1 n = new ZacetnaStran1();
            n.setVisible(true);
            n.setPoizvedba(poizvedba);
            this.dispose();
        }
        else{
            ZacetnaStran1_1 n = new ZacetnaStran1_1();
            n.setVisible(true);
            n.setPoizvedba(poizvedba);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnNazajActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        ticket2Panel.setBorder(BorderFactory.createLineBorder(new Color (0,204,204),0));
        ticket1Panel.setBorder(BorderFactory.createLineBorder(new Color (0,204,204),5));
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        ticket2Panel.setBorder(BorderFactory.createLineBorder(new Color (0,204,204),5));
        ticket1Panel.setBorder(BorderFactory.createLineBorder(new Color (0,204,204),0));
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetalskeKarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetalskeKarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetalskeKarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetalskeKarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LetalskeKarte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DepDate4;
    private javax.swing.JLabel DepDate5;
    private javax.swing.JLabel DepDate6;
    private javax.swing.JLabel DepDate7;
    private javax.swing.JLabel DepartureTime;
    private javax.swing.JLabel DepartureTime1;
    private javax.swing.JLabel DepartureTime2;
    private javax.swing.JLabel DepartureTime3;
    private javax.swing.JPanel FlightDep;
    private javax.swing.JPanel FlightDep1;
    private javax.swing.JPanel FlightDep2;
    private javax.swing.JPanel FlightDep3;
    private javax.swing.JLabel airportA;
    private javax.swing.JLabel airportA1;
    private javax.swing.JLabel airportA2;
    private javax.swing.JLabel airportA3;
    private javax.swing.JLabel airportA4;
    private javax.swing.JLabel airportA7;
    private javax.swing.JLabel airportB;
    private javax.swing.JLabel airportB1;
    private javax.swing.JLabel airportB2;
    private javax.swing.JLabel airportB3;
    private javax.swing.JLabel arrDate;
    private javax.swing.JLabel arrDate1;
    private javax.swing.JLabel arrDate2;
    private javax.swing.JLabel arrDate3;
    private javax.swing.JLabel arrivalTime;
    private javax.swing.JLabel arrivalTime1;
    private javax.swing.JLabel arrivalTime2;
    private javax.swing.JLabel arrivalTime3;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnIzberi;
    private javax.swing.JButton btnNazaj;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel depDate;
    private javax.swing.JLabel depDate1;
    private javax.swing.JLabel depDate2;
    private javax.swing.JLabel depDate3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel pricePanel;
    private javax.swing.JPanel pricePanel1;
    private javax.swing.JPanel ticket1Panel;
    private javax.swing.JPanel ticket2Panel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
