/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poletneznano;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author anjabrelih
 */
public class Placilo extends javax.swing.JFrame {
    
    Poizvedba poizvedba;
    Podatki podatki;

    /**
     * Creates new form ZacetnaStran1
     */
    public Placilo() {
        initComponents();
    }
    
    public void setPoizvedba(Poizvedba poizvedba){
        this.poizvedba=poizvedba;
    }
    
    public void setPodatki(Podatki podatki){
        this.podatki=podatki;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        placiloPodatki = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCardName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        noCard = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        noCVC = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        noYear = new javax.swing.JComboBox<>();
        noMonth = new javax.swing.JComboBox<>();
        btnPlacaj = new javax.swing.JButton();
        btnNazaj = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        DepDate8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        DepDate9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        DepDate10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        DepDate11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(957, 736));

        background.setBackground(new java.awt.Color(255, 255, 255));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel21.setText("Elektronski naslov");

        txtEmail.setBackground(new java.awt.Color(204, 255, 255));
        txtEmail.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel23.setText("Ime in priimek na kartici");

        txtCardName.setBackground(new java.awt.Color(204, 255, 255));
        txtCardName.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel24.setText("Številka kartice");

        noCard.setBackground(new java.awt.Color(204, 255, 255));
        noCard.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        noCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noCardKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel25.setText("CVC koda");

        noCVC.setBackground(new java.awt.Color(204, 255, 255));
        noCVC.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        noCVC.setMaximumSize(new java.awt.Dimension(80, 23));
        noCVC.setMinimumSize(new java.awt.Dimension(80, 23));
        noCVC.setPreferredSize(new java.awt.Dimension(80, 23));
        noCVC.setSize(new java.awt.Dimension(80, 23));
        noCVC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noCVCKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel26.setText("Datum veljavnosti");

        noYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        noYear.setMaximumSize(new java.awt.Dimension(72, 23));
        noYear.setSize(new java.awt.Dimension(72, 23));

        noMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        noMonth.setSelectedIndex(11);
        noMonth.setMaximumSize(new java.awt.Dimension(72, 23));
        noMonth.setSize(new java.awt.Dimension(72, 23));

        javax.swing.GroupLayout placiloPodatkiLayout = new javax.swing.GroupLayout(placiloPodatki);
        placiloPodatki.setLayout(placiloPodatkiLayout);
        placiloPodatkiLayout.setHorizontalGroup(
            placiloPodatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placiloPodatkiLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(placiloPodatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(txtEmail)
                    .addComponent(txtCardName)
                    .addComponent(noCard)
                    .addGroup(placiloPodatkiLayout.createSequentialGroup()
                        .addGroup(placiloPodatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(noCVC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(placiloPodatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(placiloPodatkiLayout.createSequentialGroup()
                                .addComponent(noMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        placiloPodatkiLayout.setVerticalGroup(
            placiloPodatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(placiloPodatkiLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addGap(0, 0, 0)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(txtCardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(placiloPodatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(placiloPodatkiLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, 0)
                        .addComponent(noCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(0, 0, 0)
                        .addComponent(noCVC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(placiloPodatkiLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, 0)
                        .addGroup(placiloPodatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noYear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnPlacaj.setBackground(new java.awt.Color(0, 204, 204));
        btnPlacaj.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnPlacaj.setText("Plačaj");
        btnPlacaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPlacaj.setMaximumSize(new java.awt.Dimension(120, 40));
        btnPlacaj.setMinimumSize(new java.awt.Dimension(100, 30));
        btnPlacaj.setSize(new java.awt.Dimension(120, 40));
        btnPlacaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacajActionPerformed(evt);
            }
        });

        btnNazaj.setBackground(new java.awt.Color(242, 242, 242));
        btnNazaj.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnNazaj.setText("Nazaj");
        btnNazaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNazaj.setMaximumSize(new java.awt.Dimension(120, 40));
        btnNazaj.setMinimumSize(new java.awt.Dimension(100, 30));
        btnNazaj.setSize(new java.awt.Dimension(120, 40));
        btnNazaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazajActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(contentPanelLayout.createSequentialGroup()
                            .addComponent(btnNazaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlacaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(placiloPodatki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placiloPodatki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlacaj, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNazaj, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        titlePanel.setBackground(new java.awt.Color(0, 204, 204));

        title.setFont(new java.awt.Font("Myanmar Sangam MN", 1, 26)); // NOI18N
        title.setText("Polet v neznano");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(title)
                .addContainerGap(732, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel5.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate8.setBackground(new java.awt.Color(255, 255, 255));
        DepDate8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate8.setForeground(new java.awt.Color(204, 255, 255));
        DepDate8.setText("1 Izbira leta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate8)
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(DepDate8)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel6.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate9.setBackground(new java.awt.Color(204, 255, 255));
        DepDate9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate9.setForeground(new java.awt.Color(204, 255, 255));
        DepDate9.setText("2 Podatki");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate9)
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(DepDate9)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel7.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate10.setBackground(new java.awt.Color(255, 255, 255));
        DepDate10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate10.setForeground(new java.awt.Color(204, 255, 255));
        DepDate10.setText("3 Plačilo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate10)
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(DepDate10)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel8.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate11.setBackground(new java.awt.Color(255, 255, 255));
        DepDate11.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate11.setText("4 Zaključek");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DepDate11)
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(DepDate11)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(957, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noCardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noCardKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {

            evt.consume();

        }
        
        
    }//GEN-LAST:event_noCardKeyTyped

    private void noCVCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noCVCKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {

            evt.consume();

        }
    }//GEN-LAST:event_noCVCKeyTyped

    private void btnPlacajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacajActionPerformed
        // TODO add your handling code here:
        // PLAČAJ
        String email = txtEmail.getText();
        String cardName = txtCardName.getText();
        String cardNo = noCard.getText();
        String codeCVC = noCVC.getText();
        
        if(email.isEmpty() || cardName.isEmpty() || cardNo.isEmpty() || codeCVC.isEmpty()){
            
            if(email.isEmpty()){
                // set bg to light red
                txtEmail.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                txtEmail.setBackground(new Color(204,255,255));
            }
            
            if(cardName.isEmpty()){
                // set bg to light red
                txtCardName.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                txtCardName.setBackground(new Color(204,255,255));
            }
            
            if(cardNo.isEmpty()){
                // set bg to light red
                noCard.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                noCard.setBackground(new Color(204,255,255));
            }
            
            if(codeCVC.isEmpty()){
                // set bg to light red
                noCVC.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                noCVC.setBackground(new Color(204,255,255));
            }
                
         
            
            JOptionPane.showMessageDialog(null, "Prosim izpolnite vsa polja.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
            
            
        }
        else{
            
            // set bg to normal
            txtEmail.setBackground(new Color(204,255,255));
            txtCardName.setBackground(new Color(204,255,255));
            
            
            if(!codeCVC.matches("\\d{3}") || !cardNo.matches("\\d{16}")){
                //oba narobe
                if(!codeCVC.matches("\\d{3}") && !cardNo.matches("\\d{16}")){
                  
                    // set bg to light red
                    noCVC.setBackground(new Color(255, 204, 203));
                    noCard.setBackground(new Color(255, 204, 203));
                    JOptionPane.showMessageDialog(null, "Prosim vnesite veljavno številko kartice in CVC kodo.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
                    
                // št. kartice narobe
                }else if(!cardNo.matches("\\d{16}")){
                    
                    // set bg to light red
                    noCard.setBackground(new Color(255, 204, 203));
                    // set bg back to normal
                    noCVC.setBackground(new Color(204,255,255));
                    JOptionPane.showMessageDialog(null, "Prosim vnesite veljavno številko kartice.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
                    
                    // cvc narobe                  
                }else{
                    
                    // set bg to light red
                    noCVC.setBackground(new Color(255, 204, 203));
                    // set bg back to normal
                    noCard.setBackground(new Color(204,255,255));
                    JOptionPane.showMessageDialog(null, "Prosim vnesite veljavno CVC kodo.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
                }
                
            }else{
                // set bg back to normal
                noCVC.setBackground(new Color(204,255,255));
                noCard.setBackground(new Color(204,255,255));
                
                final JOptionPane optionPane = new JOptionPane("Plačilo se izvaja.", JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, null, new Object[]{}, null);
                final JDialog dialog = new JDialog();
                dialog.setTitle("");
                dialog.setSize(200,200);
            
                dialog.setModal(true);
                dialog.setLocationRelativeTo(null);
            
                dialog.setContentPane(optionPane);

                dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                dialog.pack();
                //dialog.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2 - getWidth()/2, (Toolkit.getDefaultToolkit().getScreenSize().height)/2 - getHeight()/2);
                //create timer to dispose of dialog after 2 seconds
                Timer timer = new Timer(2000, new AbstractAction() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        dialog.dispose();
                    }
                });
                timer.setRepeats(false);//the timer should only go off once

                //start timer to close JDialog as dialog modal we must start the timer before its visible
                timer.start();
            
                dialog.setVisible(true);
         
            
                Nakup nakup = new Nakup(cardName, email, cardNo);
            
            
                Potrdilo n = new Potrdilo();
                n.setVisible(true);
                n.setNakup(nakup);
                n.setPodatki(podatki);
                n.setPoizvedba(poizvedba);
                this.dispose();
                
            }
           
        }                
        
    }//GEN-LAST:event_btnPlacajActionPerformed

    private void btnNazajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazajActionPerformed
        // TODO add your handling code here:
        
        //NAZAJ
        Potniki n = new Potniki();
        n.setVisible(true);
        n.setPoizvedba(poizvedba);
        n.setPodatki(podatki);
        this.dispose();
        
    }//GEN-LAST:event_btnNazajActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Vnesite podatke za plačilo rezerviranega leta.\n"
    + "Pazite, da so vnešeni podatki pravilni.\n"
    + "\n"
    + "Vnesite elektronski naslov na katerega boste prejeli potrdilo o rezervaciji ter račun.\n"
    + "\n"
    + "Vnesite ime in priimek lastnika kartice.\n"
    + "\n"
    + "Vnesite šestnajst mestno številko kartice.\n"
    + "\n"
    + "CVC kodo in datum veljavnosti najdete na zadnji strani kartice.", "Pomoč pri izpolnjevanju", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Placilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Placilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Placilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Placilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Placilo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DepDate10;
    private javax.swing.JLabel DepDate11;
    private javax.swing.JLabel DepDate8;
    private javax.swing.JLabel DepDate9;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnNazaj;
    private javax.swing.JButton btnPlacaj;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField noCVC;
    private javax.swing.JTextField noCard;
    private javax.swing.JComboBox<String> noMonth;
    private javax.swing.JComboBox<String> noYear;
    private javax.swing.JPanel placiloPodatki;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtCardName;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
