/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poletneznano;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author anjabrelih
 */
public class Potniki extends javax.swing.JFrame {
    
    Poizvedba poizvedba;
    Podatki podatki;
    
    

    
    /**
     * Creates new form ZacetnaStran1
     */
    public Potniki() {
        initComponents();
    }
    public void setPoizvedba(Poizvedba poizvedba){
        this.poizvedba=poizvedba;
        
    }
    
    public void setPodatki(Podatki podatki){
        this.podatki=podatki;
        
        if(podatki.getNamePass1() != null){
            namePass1.setText(podatki.getNamePass1());
            surnamePass1.setText(podatki.getSurnamePass1());
            potniList1.setText(podatki.getPotniList1());
            address1.setText(podatki.getAddress1());
            zipCode1.setText(podatki.getZipCode1());
            city1.setText(podatki.getCity1());
            
            namePass2.setText(podatki.getNamePass2());
            surnamePass2.setText(podatki.getSurnamePass2());
            potniList2.setText(podatki.getPotniList2());
            address2.setText(podatki.getAddress2());
            zipCode2.setText(podatki.getZipCode2());
            city2.setText(podatki.getCity2());
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel9 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        potnik1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        namePass1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        surnamePass1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        potniList1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        zipCode1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        city1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lug20_1 = new javax.swing.JCheckBox();
        lug30_1 = new javax.swing.JCheckBox();
        lug40_1 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        razred1 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        meal1 = new javax.swing.JComboBox<>();
        potnik2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        namePass2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        surnamePass2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        potniList2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        address2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        zipCode2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        city2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lug20_2 = new javax.swing.JCheckBox();
        lug30_2 = new javax.swing.JCheckBox();
        lug40_2 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        meal2 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        razred2 = new javax.swing.JComboBox<>();
        Naprej = new javax.swing.JButton();
        btnNazaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        DepDate8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        DepDate9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        DepDate10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        DepDate11 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(957, 736));
        setSize(new java.awt.Dimension(957, 736));

        background.setBackground(new java.awt.Color(255, 255, 255));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        potnik1.setPreferredSize(new java.awt.Dimension(779, 222));

        jLabel21.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel21.setText("Ime");

        namePass1.setBackground(new java.awt.Color(204, 255, 255));
        namePass1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        namePass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                namePass1MouseEntered(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel22.setText("Priimek");

        surnamePass1.setBackground(new java.awt.Color(204, 255, 255));
        surnamePass1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel23.setText("Številka potnega lista");

        potniList1.setBackground(new java.awt.Color(204, 255, 255));
        potniList1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namePass1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(surnamePass1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(potniList1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namePass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(surnamePass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(potniList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel24.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel24.setText("Ulica in hišna številka");

        address1.setBackground(new java.awt.Color(204, 255, 255));
        address1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel25.setText("Poštna številka");

        zipCode1.setBackground(new java.awt.Color(204, 255, 255));
        zipCode1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        zipCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCode1ActionPerformed(evt);
            }
        });
        zipCode1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zipCode1KeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel26.setText("Kraj");

        city1.setBackground(new java.awt.Color(204, 255, 255));
        city1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25))
                    .addComponent(jLabel26))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel27.setText("Vključeno imate 20 kg prtljage.");

        jLabel28.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel28.setText("Dodaj prtljago:");

        lug20_1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        lug20_1.setText("20 kg za 12€.");

        lug30_1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        lug30_1.setText("30 kg za 21€.");
        lug30_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lug30_1ActionPerformed(evt);
            }
        });

        lug40_1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        lug40_1.setText("40 kg za 29€.");
        lug40_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lug40_1ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel31.setText("Razred:");

        razred1.setBackground(new java.awt.Color(204, 255, 255));
        razred1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ekonomski", "poslovni" }));

        jLabel32.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel32.setText("Obrok:");

        meal1.setBackground(new java.awt.Color(204, 255, 255));
        meal1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mesni", "vegetrjanski", "veganski" }));

        javax.swing.GroupLayout potnik1Layout = new javax.swing.GroupLayout(potnik1);
        potnik1.setLayout(potnik1Layout);
        potnik1Layout.setHorizontalGroup(
            potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(potnik1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potnik1Layout.createSequentialGroup()
                        .addComponent(lug20_1)
                        .addGap(18, 18, 18)
                        .addComponent(lug30_1)
                        .addGap(18, 18, 18)
                        .addComponent(lug40_1))
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, potnik1Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, potnik1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(razred1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        potnik1Layout.setVerticalGroup(
            potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potnik1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potnik1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addGap(0, 0, 0)
                        .addGroup(potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lug20_1)
                            .addComponent(lug30_1)
                            .addComponent(lug40_1)))
                    .addGroup(potnik1Layout.createSequentialGroup()
                        .addGroup(potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(razred1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(potnik1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(meal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );

        potnik2.setPreferredSize(new java.awt.Dimension(779, 222));

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel12.setText("Ime");

        namePass2.setBackground(new java.awt.Color(204, 255, 255));
        namePass2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel13.setText("Priimek");

        surnamePass2.setBackground(new java.awt.Color(204, 255, 255));
        surnamePass2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel14.setText("Številka potnega lista");

        potniList2.setBackground(new java.awt.Color(204, 255, 255));
        potniList2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namePass2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(surnamePass2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(potniList2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namePass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(surnamePass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(potniList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel15.setText("Ulica in hišna številka");

        address2.setBackground(new java.awt.Color(204, 255, 255));
        address2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel16.setText("Poštna številka");

        zipCode2.setBackground(new java.awt.Color(204, 255, 255));
        zipCode2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        zipCode2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zipCode2KeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel17.setText("Kraj");

        city2.setBackground(new java.awt.Color(204, 255, 255));
        city2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(address2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(city2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addComponent(jLabel17))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel18.setText("Vključeno imate 20 kg prtljage.");

        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel19.setText("Dodaj prtljago:");

        lug20_2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        lug20_2.setText("20 kg za 12€.");

        lug30_2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        lug30_2.setText("30 kg za 21€.");
        lug30_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lug30_2ActionPerformed(evt);
            }
        });

        lug40_2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        lug40_2.setText("40 kg za 29€.");
        lug40_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lug40_2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel20.setText("Obrok:");

        meal2.setBackground(new java.awt.Color(204, 255, 255));
        meal2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mesni", "vegetrjanski", "veganski" }));

        jLabel30.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel30.setText("Razred:");

        razred2.setBackground(new java.awt.Color(204, 255, 255));
        razred2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ekonomski", "poslovni" }));

        javax.swing.GroupLayout potnik2Layout = new javax.swing.GroupLayout(potnik2);
        potnik2.setLayout(potnik2Layout);
        potnik2Layout.setHorizontalGroup(
            potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(potnik2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potnik2Layout.createSequentialGroup()
                        .addComponent(lug20_2)
                        .addGap(18, 18, 18)
                        .addComponent(lug30_2)
                        .addGap(18, 18, 18)
                        .addComponent(lug40_2))
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, potnik2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, potnik2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(razred2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        potnik2Layout.setVerticalGroup(
            potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potnik2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(razred2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(meal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(potnik2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, 0)
                        .addGroup(potnik2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lug20_2)
                            .addComponent(lug30_2)
                            .addComponent(lug40_2))))
                .addGap(26, 26, 26))
        );

        Naprej.setBackground(new java.awt.Color(0, 204, 204));
        Naprej.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        Naprej.setText("Naprej");
        Naprej.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Naprej.setMaximumSize(new java.awt.Dimension(120, 40));
        Naprej.setMinimumSize(new java.awt.Dimension(100, 30));
        Naprej.setSize(new java.awt.Dimension(120, 40));
        Naprej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaprejActionPerformed(evt);
            }
        });

        btnNazaj.setBackground(new java.awt.Color(242, 242, 242));
        btnNazaj.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnNazaj.setText("Nazaj");
        btnNazaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNazaj.setMaximumSize(new java.awt.Dimension(120, 40));
        btnNazaj.setMinimumSize(new java.awt.Dimension(100, 30));
        btnNazaj.setSize(new java.awt.Dimension(120, 40));
        btnNazaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazajActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel2.setText("Potnik 1");

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        jLabel3.setText("Potnik 2");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jButton1.setText("?");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(potnik2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                                .addComponent(potnik1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                                .addGroup(contentPanelLayout.createSequentialGroup()
                                    .addComponent(btnNazaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Naprej, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(14, 14, 14))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(potnik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(potnik2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Naprej, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNazaj, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        titlePanel.setBackground(new java.awt.Color(0, 204, 204));

        title.setFont(new java.awt.Font("Myanmar Sangam MN", 1, 26)); // NOI18N
        title.setText("Polet v neznano");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel5.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate8.setBackground(new java.awt.Color(255, 255, 255));
        DepDate8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate8.setForeground(new java.awt.Color(204, 255, 255));
        DepDate8.setText("1 Izbira leta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate8)
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(DepDate8)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel6.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate9.setBackground(new java.awt.Color(204, 255, 255));
        DepDate9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate9.setForeground(new java.awt.Color(204, 255, 255));
        DepDate9.setText("2 Podatki");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate9)
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(DepDate9)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel7.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate10.setBackground(new java.awt.Color(255, 255, 255));
        DepDate10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate10.setText("3 Plačilo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate10)
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(DepDate10)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel8.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate11.setBackground(new java.awt.Color(255, 255, 255));
        DepDate11.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate11.setText("4 Zaključek");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate11)
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(DepDate11)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(957, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NaprejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaprejActionPerformed
        // TODO add your handling code here:
        
        //NAPREJ
        String name1=namePass1.getText();
        String surname1=surnamePass1.getText();
        String passport1=potniList1.getText();
        String addr1=address1.getText();
        String zCode1=zipCode1.getText();
        String pCity1=city1.getText();
        
        String name2=namePass2.getText();
        String surname2=surnamePass2.getText();
        String passport2=potniList2.getText();
        String addr2=address2.getText();
        String zCode2=zipCode2.getText();
        String pCity2=city2.getText();
        
        
        
        if(name1.isEmpty() || surname1.isEmpty() || name2.isEmpty() || surname2.isEmpty() || passport1.isEmpty() || passport2.isEmpty() || addr1.isEmpty() || addr2.isEmpty() || zCode1.isEmpty() || zCode2.isEmpty() || pCity1.isEmpty() || pCity2.isEmpty()){
            
            // POTNIK 1
            if(name1.isEmpty()){
                // set bg to light red
                namePass1.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                namePass1.setBackground(new Color(204,255,255));
            }
                
            if(surname1.isEmpty()){
                // set bg to light red
                surnamePass1.setBackground(new Color(255, 204, 203));
            }
            else{
                // set bg back to normal
                surnamePass1.setBackground(new Color(204,255,255));
            }
            
            if(passport1.isEmpty()){
                // set bg to light red
                potniList1.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                potniList1.setBackground(new Color(204,255,255));
            }
            
            if(addr1.isEmpty()){
                // set bg to light red
                address1.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                address1.setBackground(new Color(204,255,255));
            }
            
            if(zCode1.isEmpty()){
                // set bg to light red
                zipCode1.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                zipCode1.setBackground(new Color(204,255,255));
            }
            
            if(pCity1.isEmpty()){
                // set bg to light red
                city1.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                city1.setBackground(new Color(204,255,255));
            }
            
            
            // POTNIK 2
            if(name2.isEmpty()){
                // set bg to light red
                namePass2.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                namePass2.setBackground(new Color(204,255,255));
            }
                
            if(surname2.isEmpty()){
                // set bg to light red
                surnamePass2.setBackground(new Color(255, 204, 203));
            }
            else{
                // set bg back to normal
                surnamePass2.setBackground(new Color(204,255,255));
            }
            
            if(passport2.isEmpty()){
                // set bg to light red
                potniList2.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                potniList2.setBackground(new Color(204,255,255));
            }
            
            if(addr2.isEmpty()){
                // set bg to light red
                address2.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                address2.setBackground(new Color(204,255,255));
            }
            
            if(zCode2.isEmpty()){
                // set bg to light red
                zipCode2.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                zipCode2.setBackground(new Color(204,255,255));
            }
            
            if(pCity2.isEmpty()){
                // set bg to light red
                city2.setBackground(new Color(255, 204, 203));
            } else{
                // set bg back to normal
                city2.setBackground(new Color(204,255,255));
            }
            
            
            // OBVESTILO
            JOptionPane.showMessageDialog(null, "Prosim izpolnite vsa polja.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
            
            
        }
        else{
            
            String zip1= zipCode1.getText();
            String zip2= zipCode2.getText();
            
            //set bg to normal
            namePass1.setBackground(new Color(204,255,255));
            surnamePass1.setBackground(new Color(204,255,255));
            potniList1.setBackground(new Color(204,255,255));
            address1.setBackground(new Color(204,255,255));
            zipCode1.setBackground(new Color(204,255,255));
            city1.setBackground(new Color(204,255,255));
            
            namePass2.setBackground(new Color(204,255,255));
            surnamePass2.setBackground(new Color(204,255,255));
            potniList2.setBackground(new Color(204,255,255));
            address2.setBackground(new Color(204,255,255));
            zipCode2.setBackground(new Color(204,255,255));
            city2.setBackground(new Color(204,255,255));
            
            
            if (!zip1.matches("\\d{4}") || !zip2.matches("\\d{4}")){
                //oba narobe
                if (!zip1.matches("\\d{4}") && !zip2.matches("\\d{4}")){
                    
                    // set bg to light red    
                    zipCode1.setBackground(new Color(255, 204, 203));
                    zipCode2.setBackground(new Color(255, 204, 203));
                    JOptionPane.showMessageDialog(null, "Prosim vnesite pravilne poštne številke.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
                
                //prvi narobe
                }else if (!zip1.matches("\\d{4}")){
                    
                    // set bg to light red
                    zipCode1.setBackground(new Color(255, 204, 203));
                    // set bg back to normal
                    zipCode2.setBackground(new Color(204,255,255));
                    JOptionPane.showMessageDialog(null, "Prosim vnesite pravilno poštno številko pri prvem potniku.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
                    
                //drugi narobe
                }else{
                    
                    // set bg to light red
                    zipCode2.setBackground(new Color(255, 204, 203));
                    // set bg back to normal
                    zipCode1.setBackground(new Color(204,255,255));
                    JOptionPane.showMessageDialog(null, "Prosim vnesite pravilno poštno številko pri drugem potniku.", "Opozorilo",JOptionPane.WARNING_MESSAGE);
                }
            }else{
                // set bg back to normal
                zipCode1.setBackground(new Color(204,255,255));
                zipCode2.setBackground(new Color(204,255,255));

                String raz1 = razred1.getSelectedItem().toString();
                String passMeal1 = meal1.getSelectedItem().toString();
                String raz2 = razred2.getSelectedItem().toString();
                String passMeal2 = meal2.getSelectedItem().toString();
            
                Podatki podatki = new Podatki(name1, name2, surname1, surname2, passport1, passport2, addr1, addr2, zCode1, zCode2, pCity1, pCity2, raz1, raz2, passMeal1, passMeal2);
            
                Placilo n = new Placilo();
                n.setVisible(true);
                n.setPodatki(podatki);
                n.setPoizvedba(poizvedba);
                this.dispose();
            }
        }   
    }//GEN-LAST:event_NaprejActionPerformed

    private void btnNazajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazajActionPerformed
        // TODO add your handling code here:
        
        // NAZAJ
        if(poizvedba.getDateB() == null){
            LetalskeKarte2 n = new LetalskeKarte2();
            n.setVisible(true);
            n.setPoizvedba(poizvedba);
            this.dispose();
        }
        else{
            LetalskeKarte n = new LetalskeKarte();
            n.setVisible(true);
            n.setPoizvedba(poizvedba);
            this.dispose();
        }
    }//GEN-LAST:event_btnNazajActionPerformed

    private void lug30_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lug30_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lug30_1ActionPerformed

    private void lug40_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lug40_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lug40_1ActionPerformed

    private void zipCode1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipCode1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {

            evt.consume();

        }
    }//GEN-LAST:event_zipCode1KeyTyped

    private void zipCode2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipCode2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {

            evt.consume();

        }
    }//GEN-LAST:event_zipCode2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Za vsakega potnika izpolnite osebne podatke, ki jih potrebujemo za rezervacijo vašega leta.\n"
    + "Pazite, da so vnešeni podatki pravilni.\n"
    + "\n"
    + "V polje Številka potnega lista vnesite številko veljavnega potnega lista za čas trajanja vašega potovanja.\n"
    + "\n"
    + "V kolikor želite dodati prtljago označite željeno možnost v polju Dodaj prtljago.\n"
    + "\n"
    + "Izberite razred v katerem želite potovati ter vrsto obroka na letalu za vsakega potnika.", "Pomoč pri izpolnjevanju", JOptionPane.INFORMATION_MESSAGE);
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lug40_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lug40_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lug40_2ActionPerformed

    private void lug30_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lug30_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lug30_2ActionPerformed

    private void namePass1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namePass1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_namePass1MouseEntered

    private void zipCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCode1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Potniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Potniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Potniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Potniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Potniki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DepDate10;
    private javax.swing.JLabel DepDate11;
    private javax.swing.JLabel DepDate8;
    private javax.swing.JLabel DepDate9;
    private javax.swing.JButton Naprej;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField address2;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnNazaj;
    private javax.swing.JTextField city1;
    private javax.swing.JTextField city2;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lug20_1;
    private javax.swing.JCheckBox lug20_2;
    private javax.swing.JCheckBox lug30_1;
    private javax.swing.JCheckBox lug30_2;
    private javax.swing.JCheckBox lug40_1;
    private javax.swing.JCheckBox lug40_2;
    private javax.swing.JComboBox<String> meal1;
    private javax.swing.JComboBox<String> meal2;
    private javax.swing.JTextField namePass1;
    private javax.swing.JTextField namePass2;
    private javax.swing.JTextField potniList1;
    private javax.swing.JTextField potniList2;
    private javax.swing.JPanel potnik1;
    private javax.swing.JPanel potnik2;
    private javax.swing.JComboBox<String> razred1;
    private javax.swing.JComboBox<String> razred2;
    private javax.swing.JTextField surnamePass1;
    private javax.swing.JTextField surnamePass2;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField zipCode1;
    private javax.swing.JTextField zipCode2;
    // End of variables declaration//GEN-END:variables
}
