/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poletneznano;

import java.awt.event.KeyEvent;

/**
 *
 * @author anjabrelih
 */
public class Potrdilo extends javax.swing.JFrame {
    
    Podatki podatki;
    Poizvedba poizvedba;
    Nakup nakup;

    /**
     * Creates new form ZacetnaStran1
     */
    public Potrdilo() {
        initComponents();
    }

    public void setPodatki(Podatki podatki){
        this.podatki=podatki;
        name1.setText(podatki.getNamePass1() + " " + podatki.getSurnamePass1());
        name2.setText(podatki.getNamePass2() + " " + podatki.getSurnamePass2());
        addre1.setText(podatki.getAddress1() + ", "+ podatki.getZipCode1()+" "+podatki.getCity1());
        addre2.setText(podatki.getAddress2() + ", "+ podatki.getZipCode2()+" "+podatki.getCity2());
        passport1.setText(podatki.getPotniList1());
        passport2.setText(podatki.getPotniList2());
        meal1.setText(podatki.getMeal1());
        meal2.setText(podatki.getMeal2());
        razred1.setText(podatki.getRazred1());
        razred2.setText(podatki.getRazred2());
        //luggage1
        //luggage2
        
    }
    
    public void setPoizvedba(Poizvedba poizvedba){
        this.poizvedba=poizvedba;
        airportA.setText(poizvedba.getAirportA());
        airportB.setText(poizvedba.getAirportB());

        dateDep1.setText(poizvedba.getDateA()+" "+ "15:30");
        dateArr1.setText(poizvedba.getDateA()+" "+ "17:50");
        
        if (poizvedba.getDateB() != null){
            airportA1.setText(poizvedba.getAirportA());
            airportB1.setText(poizvedba.getAirportB());
            dateDep2.setText(poizvedba.getDateB()+" "+ "15:30");
            dateArr2.setText(poizvedba.getDateB()+" "+ "17:50");   
        }else{
            airportA1.setText("");
            airportB1.setText("");
            dateDep2.setText("");
            dateArr2.setText("");
            frajer.setText("");
        }
        
    }
    
    public void setNakup(Nakup nakup){
        this.nakup=nakup;
        cardName.setText(nakup.getCardName());
        email.setText(nakup.getEmail());
        cardNumber.setText("XXXX-XXXX-XXXX-"+nakup.getCardNo().substring(nakup.getCardNo().length()-4));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        btnKoncaj = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        airportA = new javax.swing.JLabel();
        airportB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateDep1 = new javax.swing.JLabel();
        dateArr1 = new javax.swing.JLabel();
        airportB1 = new javax.swing.JLabel();
        dateDep2 = new javax.swing.JLabel();
        frajer = new javax.swing.JLabel();
        airportA1 = new javax.swing.JLabel();
        dateArr2 = new javax.swing.JLabel();
        potnik1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        addre1 = new javax.swing.JLabel();
        passport1 = new javax.swing.JLabel();
        luggage1 = new javax.swing.JLabel();
        meal1 = new javax.swing.JLabel();
        potnik2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        meal2 = new javax.swing.JLabel();
        luggage2 = new javax.swing.JLabel();
        passport2 = new javax.swing.JLabel();
        addre2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        potnik3 = new javax.swing.JLabel();
        cardName = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        cardNumber = new javax.swing.JLabel();
        potnik4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        razred1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        razred2 = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        DepDate8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        DepDate9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        DepDate10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        DepDate11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(957, 736));

        background.setBackground(new java.awt.Color(255, 255, 255));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnKoncaj.setBackground(new java.awt.Color(0, 204, 204));
        btnKoncaj.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnKoncaj.setText("Končaj");
        btnKoncaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnKoncaj.setMaximumSize(new java.awt.Dimension(120, 40));
        btnKoncaj.setMinimumSize(new java.awt.Dimension(100, 30));
        btnKoncaj.setSize(new java.awt.Dimension(120, 40));
        btnKoncaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoncajActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        airportA.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        airportA.setText("Letališče A");

        airportB.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        airportB.setText("Letališče B");

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel3.setText("-");

        dateDep1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        dateDep1.setText("Datum + ura A");

        dateArr1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        dateArr1.setText("Datum + ura B");

        airportB1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        airportB1.setText("Letališče B");

        dateDep2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        dateDep2.setText("Datum + ura B");

        frajer.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        frajer.setText("-");

        airportA1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        airportA1.setText("Letališče A");

        dateArr2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        dateArr2.setText("Datum + ura A");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(airportA)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(dateDep1))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateArr1)
                    .addComponent(airportB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(airportB1)
                        .addGap(10, 10, 10)
                        .addComponent(frajer))
                    .addComponent(dateDep2))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateArr2)
                    .addComponent(airportA1))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airportB1)
                            .addComponent(airportA1)
                            .addComponent(frajer))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateDep2)
                            .addComponent(dateArr2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airportA)
                            .addComponent(airportB)
                            .addComponent(jLabel3))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateDep1)
                            .addComponent(dateArr1))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        potnik1.setBackground(new java.awt.Color(0, 204, 204));
        potnik1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        potnik1.setForeground(new java.awt.Color(0, 204, 204));
        potnik1.setText("Potnik 1");

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel6.setText("Ime in priimek:");

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel9.setText("Naslov:");

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel11.setText("Potni list:");

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel12.setText("Prtljaga:");

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel13.setText("Meni:");

        name1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        name1.setText("Anja Brelih");

        addre1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        addre1.setText("Beblerjeva ulica 6, 5280 Idrija");

        passport1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        passport1.setText("PB1234567");

        luggage1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        luggage1.setText("20 kg");

        meal1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        meal1.setText("mesni");

        potnik2.setBackground(new java.awt.Color(0, 204, 204));
        potnik2.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        potnik2.setForeground(new java.awt.Color(0, 204, 204));
        potnik2.setText("Potnik 2");

        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel19.setText("Ime in priimek:");

        jLabel20.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel20.setText("Naslov:");

        jLabel21.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel21.setText("Potni list:");

        jLabel22.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel22.setText("Prtljaga:");

        jLabel23.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel23.setText("Meni:");

        meal2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        meal2.setText("mesni");

        luggage2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        luggage2.setText("20 kg");

        passport2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        passport2.setText("PB1234567");

        addre2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        addre2.setText("Beblerjeva ulica 6, 5280 Idrija");

        name2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        name2.setText("Anja Brelih");

        potnik3.setBackground(new java.awt.Color(0, 204, 204));
        potnik3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        potnik3.setForeground(new java.awt.Color(0, 204, 204));
        potnik3.setText("Podatki o plačilu");

        cardName.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        cardName.setText("Anja Brelih");

        email.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        email.setText("nekineki@gmail.com");

        cardNumber.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        cardNumber.setText("XXXX-XXXX-XXXX-1234");

        potnik4.setBackground(new java.awt.Color(51, 51, 51));
        potnik4.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        potnik4.setText(" Skupaj: 157€ ");
        potnik4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));

        jLabel32.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel32.setText("Razred:");

        razred1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        razred1.setText("ekonomski");

        jLabel34.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel34.setText("Razred:");

        razred2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        razred2.setText("ekonomski");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(razred1)
                            .addComponent(addre1)
                            .addComponent(name1)
                            .addComponent(passport1)
                            .addComponent(luggage1)
                            .addComponent(meal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potnik3)
                            .addComponent(cardName)
                            .addComponent(email)
                            .addComponent(cardNumber))
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(potnik1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(potnik4)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potnik2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel34))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(razred2)
                                    .addComponent(addre2)
                                    .addComponent(name2)
                                    .addComponent(passport2)
                                    .addComponent(luggage2)
                                    .addComponent(meal2))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potnik1)
                    .addComponent(potnik4))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(name1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(potnik3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardNumber)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(addre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(passport1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(luggage1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(meal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(razred1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(potnik2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(name2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(addre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(passport2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(luggage2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(meal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(razred2))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKoncaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnKoncaj, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        titlePanel.setBackground(new java.awt.Color(0, 204, 204));

        title.setFont(new java.awt.Font("Myanmar Sangam MN", 1, 26)); // NOI18N
        title.setText("Polet v neznano");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(title)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel5.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate8.setBackground(new java.awt.Color(255, 255, 255));
        DepDate8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate8.setForeground(new java.awt.Color(204, 255, 255));
        DepDate8.setText("1 Izbira leta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate8)
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(DepDate8)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel6.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate9.setBackground(new java.awt.Color(204, 255, 255));
        DepDate9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate9.setForeground(new java.awt.Color(204, 255, 255));
        DepDate9.setText("2 Podatki");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate9)
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(DepDate9)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel7.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate10.setBackground(new java.awt.Color(255, 255, 255));
        DepDate10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate10.setForeground(new java.awt.Color(204, 255, 255));
        DepDate10.setText("3 Plačilo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DepDate10)
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(DepDate10)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBounds(new java.awt.Rectangle(0, 0, 240, 20));
        jPanel8.setMaximumSize(new java.awt.Dimension(340, 20));

        DepDate11.setBackground(new java.awt.Color(255, 255, 255));
        DepDate11.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DepDate11.setForeground(new java.awt.Color(204, 255, 255));
        DepDate11.setText("4 Zaključek");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DepDate11)
                .addGap(20, 20, 20))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(DepDate11)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        setSize(new java.awt.Dimension(957, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKoncajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoncajActionPerformed
        // TODO add your handling code here:
        
        // KONČAJ
        
        ZacetnaStran1 n = new ZacetnaStran1();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKoncajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Potrdilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Potrdilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Potrdilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Potrdilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Potrdilo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DepDate10;
    private javax.swing.JLabel DepDate11;
    private javax.swing.JLabel DepDate8;
    private javax.swing.JLabel DepDate9;
    private javax.swing.JLabel addre1;
    private javax.swing.JLabel addre2;
    private javax.swing.JLabel airportA;
    private javax.swing.JLabel airportA1;
    private javax.swing.JLabel airportB;
    private javax.swing.JLabel airportB1;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnKoncaj;
    private javax.swing.JLabel cardName;
    private javax.swing.JLabel cardNumber;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel dateArr1;
    private javax.swing.JLabel dateArr2;
    private javax.swing.JLabel dateDep1;
    private javax.swing.JLabel dateDep2;
    private javax.swing.JLabel email;
    private javax.swing.JLabel frajer;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel luggage1;
    private javax.swing.JLabel luggage2;
    private javax.swing.JLabel meal1;
    private javax.swing.JLabel meal2;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel passport1;
    private javax.swing.JLabel passport2;
    private javax.swing.JLabel potnik1;
    private javax.swing.JLabel potnik2;
    private javax.swing.JLabel potnik3;
    private javax.swing.JLabel potnik4;
    private javax.swing.JLabel razred1;
    private javax.swing.JLabel razred2;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
